services:
  backend:
    build:
      context: ./backendFlask
    ports:
      - "5000:5000"
    volumes:
      - ./backendFlask:/app
    depends_on:
      - db
    env_file:
      - ./backendFlask/.env

  frontend:
    build:
      context: ./frontendReact
    ports:
      - "3000:80"
    volumes:
      - ./frontendReact:/app
    env_file:
      - ./frontendReact/.env


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FieldStatDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: